### ISSUE TITLE
Grid Data folder not found 

### ISSUE THREAD

**Issue by ShanawarShahbaz** [FESOM/pyfesom2#102]
* pyfesom2 version: https://github.com/FESOM/pyfesom2
* Python version: 3.6
* Operating System: ubuntu

### Description

I am trying to follow the tutorial you shared, I haven't downloaded 15GB mesh, instead, I am trying to use the lightweight mesh, 

As per the tutrial it is state to use : 
"Alternative would be to use very light weight mesh that comes with pyfesom2 in the tests/data/pi-grid/ and example data on this mesh in tests/data/pi-data."

but there is no "pi-data" directory in tests.

### What I Did#############
I run the below command: 
note:
i run it with multi combination of command i.e in the second agrument I tire with"/pi-results"
then create my own directory of pi-data. 
but no luck .

pfinterp /home/shan/pyfesom2/tests/data/pi-grid/pickle_mesh_py3_fesom2  /home/shan/pyfesom2/tests/data/pi-data/ shan

```

If there was a crash, please include the traceback here.
```
sgeo is not installed, conversion to Geo formats like Geotiff (fesom2GeoFormat) will not work.
Mesh path:                     /home/shan/pyfesom2/tests/data/pi-grid/pickle_mesh_py3_fesom2
Input file path:               /home/shan/pyfesom2/tests/data/pi-data/
Name of the variable:          shan
Years:                         1948
Depths:                         0
Bounding box:                  [-180.0, 180.0, -80.0, 90.0]
Number of points along sides:  (360, 170)
Radius of influence (in m.):   80000
Nearest neighbors to use:      5
Timesteps index:               -1
Quiet?:                        False
Output file:                   out.nc
Euler angles of mesh rotation: (0.0, 0.0, 0.0)
Interpolation method:          nn
/home/shan/pyfesom2/tests/data/pi-grid/pickle_mesh_py3_fesom2/pickle_mesh_py3_fesom2
The usepickle == True
The pickle file for FESOM2 DO NOT exists
The mesh will be saved to /home/shan/pyfesom2/tests/data/pi-grid/pickle_mesh_py3_fesom2/pickle_mesh_py3_fesom2
Traceback (most recent call last):
  File "/root/anaconda3/envs/pyfesom2/bin/pfinterp", line 11, in <module>
    load_entry_point('pyfesom2', 'console_scripts', 'pfinterp')()
  File "/home/shan/pyfesom2/pyfesom2/pfinterp.py", line 290, in pfinterp
    mesh = load_mesh(args.meshpath, abg=args.abg, usepickle=True, usejoblib=False)
  File "/home/shan/pyfesom2/pyfesom2/load_mesh_data.py", line 68, in load_mesh
    mesh = fesom_mesh(path=path, abg=abg)
  File "/home/shan/pyfesom2/pyfesom2/load_mesh_data.py", line 174, in __init__
    self.read2d()
  File "/home/shan/pyfesom2/pyfesom2/load_mesh_data.py", line 183, in read2d
    names=["node_number", "x", "y", "flag"],
  File "/root/anaconda3/envs/pyfesom2/lib/python3.6/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/root/anaconda3/envs/pyfesom2/lib/python3.6/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/root/anaconda3/envs/pyfesom2/lib/python3.6/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/root/anaconda3/envs/pyfesom2/lib/python3.6/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/root/anaconda3/envs/pyfesom2/lib/python3.6/site-packages/pandas/io/parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 374, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File /home/shan/pyfesom2/tests/data/pi-grid/pickle_mesh_py3_fesom2/nod2d.out does not exist: '/home/shan/pyfesom2/tests/data/pi-grid/pickle_mesh_py3_fesom2/nod2d.out'

**Comment by koldunovn** [comment]
Hi @ShanawarShahbaz . Looks like you provided the path to the pickle file
```
/home/shan/pyfesom2/tests/data/pi-grid/pickle_mesh_py3_fesom2
```
not to the mesh folder:
```
/home/shan/pyfesom2/tests/data/pi-grid/
```
You also provide your user name `shan` instead of the name of the FESOM2 variable (e. g. `temp`).
So the proper command in your case would be:
```
pfinterp /home/shan/pyfesom2/tests/data/pi-grid/ /home/shan/pyfesom2/tests/data/pi-data/ temp
```

**Comment by ShanawarShahbaz** [comment]
but there is no folder of "pi-data" in the /tests/data/.

It has only three folders name below : 
1. baseline_images 
2.  pi-grid
 3.  pi-results

**Comment by koldunovn** [comment]
@ShanawarShahbaz Well, it's pi-results then, sorry for the confusion. I will change it in the description.

**Comment by ShanawarShahbaz** [comment]
@koldunovn Thanks for the correction, Perhaps when I tried to run the below command, another exception occur.
pfinterp /home/shan/pyfesom2/tests/data/pi-grid/ /home/shan/pyfesom2/tests/data/pi-results/ shan.

=================TRACE==================

Mesh path:                     /home/shan/pyfesom2/tests/data/pi-grid/
Input file path:               /home/shan/pyfesom2/tests/data/pi-results/
Name of the variable:          shan
Years:                         1948
Depths:                         0
Bounding box:                  [-180.0, 180.0, -80.0, 90.0]
Number of points along sides:  (360, 170)
Radius of influence (in m.):   80000
Nearest neighbors to use:      5
Timesteps index:               -1
Quiet?:                        False
Output file:                   out.nc
Euler angles of mesh rotation: (0.0, 0.0, 0.0)
Interpolation method:          nn
/home/shan/pyfesom2/tests/data/pi-grid/pickle_mesh_py3_fesom2
The usepickle == True)
The pickle file for FESOM2 exists.
The mesh will be loaded from /home/shan/pyfesom2/tests/data/pi-grid/pickle_mesh_py3_fesom2
Depth is None, 3d field will be returned
Traceback (most recent call last):
  File "/root/anaconda3/envs/pyfesom2/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 198, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/root/anaconda3/envs/pyfesom2/lib/python3.6/site-packages/xarray/backends/lru_cache.py", line 53, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/home/shan/pyfesom2/tests/data/pi-results/shan.fesom.1948.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False))]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/pyfesom2/bin/pfinterp", line 11, in <module>
    load_entry_point('pyfesom2', 'console_scripts', 'pfinterp')()
  File "/home/shan/pyfesom2/pyfesom2/pfinterp.py", line 313, in pfinterp
    compute=False,
  File "/home/shan/pyfesom2/pyfesom2/load_mesh_data.py", line 616, in get_data
    dataset = xr.open_mfdataset(paths, combine="by_coords", **kwargs)
  File "/root/anaconda3/envs/pyfesom2/lib/python3.6/site-packages/xarray/backends/api.py", line 908, in open_mfdataset
    datasets = [open_(p, **open_kwargs) for p in paths]
  File "/root/anaconda3/envs/pyfesom2/lib/python3.6/site-packages/xarray/backends/api.py", line 908, in <listcomp>
    datasets = [open_(p, **open_kwargs) for p in paths]
  File "/root/anaconda3/envs/pyfesom2/lib/python3.6/site-packages/xarray/backends/api.py", line 502, in open_dataset
    filename_or_obj, group=group, lock=lock, **backend_kwargs
  File "/root/anaconda3/envs/pyfesom2/lib/python3.6/site-packages/xarray/backends/netCDF4_.py", line 358, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/root/anaconda3/envs/pyfesom2/lib/python3.6/site-packages/xarray/backends/netCDF4_.py", line 314, in __init__
    self.format = self.ds.data_model
  File "/root/anaconda3/envs/pyfesom2/lib/python3.6/site-packages/xarray/backends/netCDF4_.py", line 367, in ds
    return self._acquire()
  File "/root/anaconda3/envs/pyfesom2/lib/python3.6/site-packages/xarray/backends/netCDF4_.py", line 361, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/root/anaconda3/envs/pyfesom2/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/root/anaconda3/envs/pyfesom2/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 186, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/root/anaconda3/envs/pyfesom2/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 204, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "netCDF4/_netCDF4.pyx", line 2321, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4/_netCDF4.pyx", line 1885, in netCDF4._netCDF4._ensure_nc_success
F**ileNotFoundError: [Errno 2] No such file or directory: b'/home/shan/pyfesom2/tests/data/pi-results/shan.fesom.1948.nc'**

**Comment by ShanawarShahbaz** [comment]
@koldunovn  I also tried to do with 'temp' variable,( just in case if it works ). so below were the results


===================TRACES===================


(pyfesom2) root@ubuntu:/home/shan/pyfesom2/tests/data/pi-results# pfinterp /home/shan/pyfesom2/tests/data/pi-grid/ /home/shan/pyfesom2/tests/data/pi-results/ temp
Mesh path:                     /home/shan/pyfesom2/tests/data/pi-grid/
Input file path:               /home/shan/pyfesom2/tests/data/pi-results/
Name of the variable:          temp
Years:                         1948
Depths:                         0
Bounding box:                  [-180.0, 180.0, -80.0, 90.0]
Number of points along sides:  (360, 170)
Radius of influence (in m.):   80000
Nearest neighbors to use:      5
Timesteps index:               -1
Quiet?:                        False
Output file:                   out.nc
Euler angles of mesh rotation: (0.0, 0.0, 0.0)
Interpolation method:          nn
/home/shan/pyfesom2/tests/data/pi-grid/pickle_mesh_py3_fesom2
The usepickle == True)
The pickle file for FESOM2 exists.
The mesh will be loaded from /home/shan/pyfesom2/tests/data/pi-grid/pickle_mesh_py3_fesom2
Depth is None, 3d field will be returned
timesteps -1
[0]
[0]
[0.0]
Model depth: 0.0
Traceback (most recent call last):
  File "/root/anaconda3/envs/pyfesom2/bin/pfinterp", line 11, in <module>
    load_entry_point('pyfesom2', 'console_scripts', 'pfinterp')()
  File "/home/shan/pyfesom2/pyfesom2/pfinterp.py", line 374, in pfinterp
    basepath=None,
  File "/home/shan/pyfesom2/pyfesom2/regriding.py", line 161, in fesom2regular
    joblib.dump(distances, distances_path)
  File "/root/anaconda3/envs/pyfesom2/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 504, in dump
    with open(filename, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: **'/Users/koldunovn/PYHTON/pyfesom2/tests/data/pi-grid/distances_3140_-180.0_180.0_-80.0_90.0_360_170_1'**

**Comment by koldunovn** [comment]
Please try to remove the `pickle_mesh_py3_fesom2` from your `/home/shan/pyfesom2/tests/data/pi-grid/` folder. It should work then. I will delete the pickle file from test directory. 

As the third argument, you have to provide the name of the variable, no the name of the user.

Please let me know if it works for you.

**Comment by ShanawarShahbaz** [comment]
@koldunovn  Thanks ,It is now working
